### ISSUE TITLE
migrate-monitors : Private minions are not handled correctly. Allow specifying target  location name for private minion.

### ISSUE THREAD

**Issue by adiosspandit** [newrelic-experimental/nr-account-migration#31]
## Description
Private minion location name end up being different in different accounts and the migration script is unable to find a matching private minion. 

## Steps to Reproduce

Create two accounts with different private minion names. Try to move to source monitor to target account. It will fail as same private minion location name is not found in target account

## Expected Behavior
Source monitor should migrate to target account without errors.

## Possible Solution

Allow passing a targetLocationName which should be used when monitor is created in target account

## Additional context

The locationName is not the same as displayed in UI. A unique locationName_SomeNumber id is created for the private location.

**Comment by adiosspandit** [comment]
This is available in a separate branch. Not merged as only 1 customer has asked for this.

**Comment by GokulKNair** [comment]
Hello Adiosspandit..I am running into an issue when attempitng this migration from one account to another for synthetics.
Probably a user error as I am new to python
I know this comment is not relevant here. Kindly let me know if you are willing to look into my issue so that I can provide more details.
Any help would be  very highly appreciated

**Comment by adiosspandit** [comment]
Could you send me some more details.
Which script are you trying and what is the error message?

**Comment by adiosspandit** [comment]
Fixed by https://github.com/newrelic-experimental/nr-account-migration/pull/39
